version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: carwash-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: carwash_db
      POSTGRES_USER: carwash_user
      POSTGRES_PASSWORD: carwash_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carwash_user -d carwash_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
